stages:
  - test

test:
  stage: test
  image: $IMAGE
  only:
    - master
    - merge_requests
  parallel:
    matrix:
      - IMAGE:
          - php:8.0-cli
          - php:8.1-cli
          - php:cli
  before_script:
    - apt-get -qq update
    - apt-get -y --no-install-recommends install git unzip
    - curl -s -L -o /dev/stdout https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer | php -- --quiet --filename=composer --install-dir=/bin
  script:
    # Install dependencies and run tests
    - composer install --no-progress --no-ansi --no-suggest
    - vendor/bin/phpunit tests
    - vendor/bin/php-cs-fixer fix --verbose --dry-run

tag:
  image: curlimages/curl:latest
  only:
    refs:
      - tags
  variables:
    GIT_STRATEGY: none
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=$CI_COMMIT_TAG "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/composer"'
